### PR TITLE
test(storage): cover successor download after failover and exit

### LINKED ISSUE #32: e2e: add SP read-failover test — GET object when primary is unreachable
## Gap

The test suite verifies the **write** path of SP redundancy — `test_storage_object_seal.sh` waits for `OBJECT_STATUS_SEALED`, which confirms secondaries signed during replication. It does **not** verify the **read** path: that an object can still be retrieved when the primary SP is unreachable.

Erasure coding is `4 data + 2 parity` chunks per `topology/default.yaml:29` → any 4 of 6 SPs are sufficient to reconstruct. Today, nothing in CI catches a regression that breaks secondary fallback.

Adjacent coverage also missing:
- Re-replication / challenge when a secondary misses a chunk
- Bucket migration flow when an SP graceful-exits

## Proposed test — `tests/test_storage_object_failover.sh`

Local only (kill-SP on remote not possible):

```
1. bucket create --primarySP sp-0
2. object put <file> → wait for OBJECT_STATUS_SEALED
3. docker pause sp-0   # or `docker network disconnect`
4. object get <same path>   → expect success, sha256 matches original
5. docker unpause sp-0
6. cleanup
```

Skip cleanly on `ENV != local` (and on topologies with < primary + 2 secondaries, matching existing guards in `test_storage_object.sh:19`).

## Remote-env variant (optional, later)

Requires a moca-cmd/SDK knob to exclude an SP endpoint from read candidates (or `SP_ENDPOINT_FILTER` applied to the gateway list used for GET). If that exists, a devnet/testnet variant could force reads to avoid the primary and verify reconstruction.

## Acceptance
- New test fails if a code change breaks read-fallback (e.g. gateway doesn't retry secondaries)
- Runs in under ~30s on local topology
- Skips gracefully on remote envs and small topologies

### PR DESCRIPTION
**Pull request by phenix3443**
## What changed
- add `tests/test_storage_object_failover.sh` to cover manual object failover on the local stack: force the original primary SP into `STATUS_FORCED_EXITING`, pause its container, reserve swap-in on a chosen successor, recover the VGF, complete swap-in, and verify the object can still be downloaded
- wait for `query-recover-p` to report `Successful` with zero failed objects before calling `completeSwapIn`, so the test matches the actual successor recovery contract instead of racing the background recover job
- verify the paused primary endpoint cannot serve the object during failover and compare the post-failover download against the original file with SHA-256
- extract shared download/checksum helpers into `tests/lib.sh` and reuse them in `tests/test_sp_exit.sh`
- strengthen `tests/test_sp_exit.sh` so graceful exit now also verifies the object can be downloaded from the successor endpoint after the original SP exits
- adjust local topology/config wiring needed by the new local-only failover coverage

## Why
Issue #32 is about validating the standard SP exit and successor takeover path with real object readability, not just metadata visibility. The suite previously missed the read path in two important places:
- manual failover after the original primary becomes unavailable
- graceful exit after primary ownership moves to a successor

This PR adds both checks and fixes a test bug we confirmed locally: `recover-vgf` only triggers background recovery, so calling `completeSwapIn` immediately can race recovery and produce a false failure even when the storage-provider logic is healthy.

## Impact
- adds a deterministic local regression test for manual successor takeover and object readability after forced primary unavailability
- upgrades graceful-exit coverage from metadata-only checks to a real successor download check
- reduces false negatives in CI/local runs by waiting for successor recovery completion before finalizing swap-in

## Validation
- `bash -n tests/lib.sh`
- `bash -n tests/test_sp_exit.sh`
- `bash -n tests/test_storage_object_failover.sh`
- `bash tests/test_sp_exit.sh local config/local.yaml`
- `bash tests/test_storage_object_failover.sh local config/local.yaml`

## Notes
- `tests/test_storage_object_failover.sh` is intentionally local-only because it pauses Docker SP containers and depends on the local `moca-cmd` sidecar
- the failover investigation showed the previous failure was a test timing issue, not a missing chain-sync step: the successor needed time to finish background recovery before `completeSwapIn`

Closes #32

### CODE REVIEW

File: tests/test_storage_object_failover.sh [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+  echo "$put_out"
+  echo "FAIL: object put did not reach uploaded/sealed state"
+  exit 1
+fi
+print_success "object put completed (SEALED)"
+
+print_test_section "Step 3: pause primary SP container"
+docker pause "$PRIMARY_SP_CONTAINER" >/dev/null
+PRIMARY_PAUSED=1
+sleep 3
```
Comment (puneet2019) [inline tests/test_storage_object_failover.sh:497]: can you add better check here? 
something that aligns with: endpoint doesn't exist/ 404

**Review by puneet2019 — APPROVED** [review]
